language: node_js
node_js:
- 10.15.3
addons:
  ssh_known_hosts:
  - 119.28.47.57:22222
script: npm run build
after_success:
- rsync -az -vv --delete -e 'ssh -p 22222' ./dist/**  root@119.28.47.57:/data/release/test-vue/dist/
before_install:
- openssl aes-256-cbc -K $encrypted_fd149d5216df_key -iv $encrypted_fd149d5216df_iv
  -in id_rsa..enc -out id_rsa. -d
